select = ['E', 'F', 'W', 'UP', 'B', 'C4', 'PL', 'RUF']

ignore = [
  'B007',
  'B905',
  'C408',
  'E731',
  'PLR0911',
  'PLR0912',
  'PLR0913',
  'PLR0915',
  'PLR2004',
  'PLW2901',
  'RUF012',
  'UP007',
  'UP032',
]

exclude = [
  'beanquery/parser/parser.py'
]

line-length = 128
target-version = 'py38'

[per-file-ignores]
'beanquery/query_env.py' = ['F811']
