name: checks
on:
  - push
  - pull_request
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install ruff
      - run: ruff check beanquery/
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt coverage
      - name: Run coverage
        # Check tests coverage. Instead of checking project coverage of
        # all the tests we check that each module is exaustively tested
        # by the dedicated units tests.
        run: |
          set -x
          echo '{

            "beanquery/parser/*": "beanquery/parser_test.py",
            "beanquery/query_render.py": "beanquery/query_render_test.py"

          }' | jq -rc 'to_entries | .[] | (.key + "=" + .value)' | while IFS='=' read src test
          do
            python -m coverage run --branch --include "$src" --omit beanquery/parser/parser.py -m unittest "$test"
            python -m coverage report --fail-under=100 -m
            python -m coverage erase
          done
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt wheel build
      - run: python -m build --no-isolation
      - run: python -m pip install dist/beanquery-*.whl
