name: checks
on:
  - push
  - pull_request
jobs:
  pylint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt pylint
      - run: python -m pylint beanquery/
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt click ply python-dateutil pytest coverage
      - run: python -m coverage run --branch -m pytest beanquery/query_parser_test.py
      - run: python -m coverage report --precision=2 --fail-under=100 beanquery/query_parser.py
