name: test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        beancount:
          - '~= 2.3.6'
          - '@ git+https://github.com/beancount/beancount.git'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - run: pip install 'beancount ${{ matrix.beancount }}'
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -p '*_test.py'
